// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gexdoytyemjzonxguvhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdleGRveXR5ZW1qem9ueGd1dmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTYyNzYsImV4cCI6MjA2OTU3MjI3Nn0.fbFOgL70B68xXQb8o7tI56c4_TwYI1x1kdDoHMtKgsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});